### 📌 FACTORIZACIÓN ###

La factorización es el proceso de descomponer una expresión matemática en el producto de sus factores más simples.
✅ Permite: 
- Simplificar expresiones algebraicas.
- Resolver ecuaciones al encontrar los valores que anulan la expresión.
- Identificar patrones y estructuras ocultas.
- Optimizar cálculos en análisis de datos y algoritmos computacionales.

### FACTORIZACIÓN DE UN MONOMIO ###

Es el proceso de descomponer un término algebraico en sus factores más simples.

Por ejemplo: 3*x + 3*y = 3*(x + y)

En Machine Learning, se usa en la preparación de datos simbólicos o algebraicos, para simplificar expresiones, extraer patrones, reducir dimensionalidad simbólica o mejorar la eficiencia de modelos simbólicos como los árboles de decisión simbólicos o modelos simbólicos interpretables.

In [5]:
# Ejercicio 1: Factorización de un Monomio
from sympy import symbols, factor

# Definir variables
x, y = symbols('x y')

# Expresión con factor común
expr = 3*x + 3*y

# Aplicar factorización
fact = factor(expr)

# Mostrar resultado
print(f'Factorización con factor común:\n   {expr} = {fact}')


Factorización con factor común:
   3*x + 3*y = 3*(x + y)


### FACTORIZACIÓN DE UN BINOMIO AL CUADRADO ###

En Machine Learning, puede utilizarse para simplificar expresiones cuadráticas simbólicas.

Por ejemplo: (x + 2)² = x² + 4x + 4.

Se usa para reducir fórmulas complejas, analizar relaciones no lineales, y facilitar la interpretación en modelos simbólicos o al aplicar técnicas de álgebra computacional en sistemas de aprendizaje automático.

In [ ]:
# ✅ Ejercicio 2 - Factorización de un Binomio al Cuadrado

from sympy import symbols, factor, expand

# Definir la variable
x = symbols('x')

# Expresión original
expr2 = (x + 2)**2

# Factorización
fact2 = factor(expr2)

# Expandir para verificar
expanded_fact2 = expand(fact2)

# Imprimir resultados
print(f'Ejercicio 2 - Binomio al Cuadrado: {expr2}')
print(f'Factorización: {fact2}')
print(f'Factorización Expandida: {expanded_fact2}')

Ejercicio 2 - Binomio al Cuadrado: (x + 2)**2
Factorización: (x + 2)**2
Factorización Expandida: x**2 + 4*x + 4


### FACTORIZACIÓN DE LA DIFERENCIA DE CUADRADOS ###

En Machine Learning, se aplica para simplificar expresiones simbólicas con términos cuadráticos.

Por ejemplo: x² − 9 = (x + 3)(x − 3).

Se usa para descomponer funciones no lineales, facilitar el análisis algebraico en modelos interpretables y optimizar cálculos en sistemas simbólicos o algoritmos basados en álgebra.


In [8]:
# Ejercicio 3: Factorización de la Diferencia de Cuadrados
expr3 = x**2 - 4
fact3 = factor(expr3)
print(f'Ejercicio 3 - Factorización de la Diferencia de Cuadrados: {expr3} = {fact3}')

Ejercicio 3 - Factorización de la Diferencia de Cuadrados: x**2 - 4 = (x - 2)*(x + 2)


### FACTORIZACIÓN POR AGRUPACIÓN ###

En Machine Learning, se puede usar para simplificar expresiones simbólicas que no tienen un patrón evidente a primera vista.

Por ejemplo: ax + ay + bx + by = (a + b)(x + y).

Se usa para reorganizar términos, encontrar estructuras comunes en expresiones complejas y facilitar el análisis simbólico en modelos basados en reglas, árboles o álgebra computacional.

In [9]:
# Definir las variables
x, y, z, a = symbols('x y z a')

# Expresión original
expr4 = x*y + x*z + a*y + a*z

# Factorización por agrupación
fact4 = factor(expr4)

# Imprimir resultados
print(f'Ejercicio 4 - Factorización por Agrupación: {expr4} = {fact4}')

Ejercicio 4 - Factorización por Agrupación: a*y + a*z + x*y + x*z = (a + x)*(y + z)


### FACTORIZACIÓN POR FACTOR COMÚN ###

En Machine Learning, se usa para simplificar expresiones algebraicas encontrando un término común entre varios.

Por ejemplo: 6x + 12 = 6(x + 2).

Se aplica para reducir expresiones simbólicas, optimizar funciones y hacer más eficientes modelos interpretables o sistemas de álgebra computacional.

In [10]:
# Ejercicio 5: Factorización por Factor Común
expr5 = 3*x + 6*y
fact5 = factor(expr5)
print(f'Ejercicio 5 - Factorización por Factor Común: {expr5} = {fact5}')

Ejercicio 5 - Factorización por Factor Común: 3*x + 6*y = 3*(x + 2*y)


### FACTORIZACIÓN DE UN TRINOMIO DE LA FORMA ###

En Machine Learning, se puede usar para simplificar expresiones cuadráticas simbólicas que modelan relaciones no lineales.

Por ejemplo: x² + 5x + 6 = (x + 2)(x + 3).

Se aplica para resolver ecuaciones, analizar funciones de costo, y optimizar expresiones simbólicas en modelos algebraicos o interpretables.

In [11]:
# Ejercicio 6: Factorización de un Trinomio de la Forma ax^2 + bx + c
expr7 = x**2 + 3*x + 2
fact7 = factor(expr7)
print(f'Ejercicio 6 - Factorización de un Trinomio de la Forma ax^2 + bx + c: {expr7} = {fact7}')

Ejercicio 6 - Factorización de un Trinomio de la Forma ax^2 + bx + c: x**2 + 3*x + 2 = (x + 1)*(x + 2)


### FACTORIZACIÓN POR SUSTITUCIÓN ###

En Machine Learning, se utiliza para simplificar expresiones complejas sustituyendo partes repetitivas por una nueva variable.

Por ejemplo: (x² + 1)² − 9 = t² − 9, donde t = x² + 1 → (t − 3)(t + 3) → ((x² + 1) − 3)((x² + 1) + 3).

Se aplica para descomponer estructuras anidadas, facilitar el análisis simbólico y optimizar modelos algebraicos o interpretables.

In [12]:
# Ejercicio 7: Factorización por sustitución
from sympy import collect #se debe importar collect

# Definir las variables
u, v, w = symbols('u v w')

# Expresión original
expr7 = 2*u*v + 3*u*w - 4*v*w

# Factorización por sustitución
factored_expr7 = collect(expr7, u)  # Agrupar términos con respecto a 'u'

# Imprimir resultados
print(f'Ejercicio 7 - Factorización por Sustitución: {expr7} = {factored_expr7}')

Ejercicio 7 - Factorización por Sustitución: 2*u*v + 3*u*w - 4*v*w = u*(2*v + 3*w) - 4*v*w


### FACTORIZACIÓN POR DIVISIÓN SINTÉTICA ###
En Machine Learning, puede aplicarse en álgebra simbólica para descomponer polinomios de alto grado.

Por ejemplo: x³ − 6x² + 11x − 6 = (x − 3)(x − 2)(x − 1).

Se usa para resolver ecuaciones polinómicas, analizar raíces y simplificar expresiones en modelos simbólicos o interpretables.

In [13]:
# Ejercicio 8: Factorización por División Sintética
expr9 = x**3 - 6*x**2 + 11*x - 6
fact9 = factor(expr9)
print(f'Ejercicio 8 - Factorización por División Sintética: {expr9} = {fact9}')

Ejercicio 8 - Factorización por División Sintética: x**3 - 6*x**2 + 11*x - 6 = (x - 3)*(x - 2)*(x - 1)


### EJERCICIOS ###

In [14]:
# Vamos aplicar algunas funciones para divertirnos con esto !!!**
# Análisis Empresarial - Costos de Producción Enunciado: Los costos de producción de una empresa están dados por 4 𝑝 2 + 20 𝑝 + 25 . Factoriza esta expresión.

def factorizar_trinomio_produccion(a, b, c):
    discriminante = b**2 - 4*a*c
    if discriminante < 0:
        return "No tiene raíces reales"
    elif discriminante == 0:  # Verificar si es un cuadrado perfecto
        # Para un cuadrado perfecto, la factorización es de la forma (√a * p + √c)^2
        raiz_a = int(a**0.5)  # Raíz cuadrada del coeficiente de p^2
        raiz_c = int(c**0.5)  # Raíz cuadrada del término constante
        return f"{a}p^2 + {b}p + {c} = ({raiz_a}p + {raiz_c})^2"
    else:
        # Calcular las raíces si no es un cuadrado perfecto
        raiz1 = (-b + discriminante**0.5) / (2 * a)
        raiz2 = (-b - discriminante**0.5) / (2 * a)
        return f"Las raíces son {raiz1} y {raiz2}"

# Ejemplo de uso
print(factorizar_trinomio_produccion(4, 20, 25))


4p^2 + 20p + 25 = (2p + 5)^2


In [15]:
#Dado el polinomio 𝑥 2 − 5 𝑥 + 6 que representa las longitudes de sépalos en el conjunto de datos de Iris, factorízalo.

def factorizar_trinomio_iris(a, b, c):
    discriminante = b**2 - 4*a*c
    if discriminante < 0:
        return "No tiene raíces reales"
    raiz1 = (-b + discriminante**0.5) / (2*a)
    raiz2 = (-b - discriminante**0.5) / (2*a)
    return f"{a}x^2 + {b}x + {c} = (x - {int(raiz1)}) (x - {int(raiz2)})"

a = 1
b = -5
c = 6
print(factorizar_trinomio_iris(a, b, c))

1x^2 + -5x + 6 = (x - 3) (x - 2)


In [16]:
#Factoriza la expresión utilizando la fórmula de la suma de cubos.

def factorizar_suma_cubos(a, b):
    """
    Esta función recibe dos números 'a' y 'b' y devuelve la factorización
    de la suma de sus cubos utilizando la fórmula de la suma de cubos.

    La fórmula para la suma de cubos es:
    a^3 + b^3 = (a + b)(a^2 - ab + b^2)
    """

    # Calcula la suma de los cubos de 'a' y 'b'
    suma_cubos = a**3 + b**3

    # Retorna la factorización usando la fórmula de la suma de cubos
    # La fórmula genera dos factores:
    # 1. (a + b): la suma directa de 'a' y 'b'
    # 2. (a^2 - ab + b^2): un trinomio con los términos al cuadrado y producto de 'a' y 'b'
    return f"{a}^3 + {b}^3 = ({a} + {b})({a**2} - {a*b} + {b**2})"

# Ejemplo de uso de la función:
a = 1  # Asigna el valor 1 a la variable 'a'
b = 3  # Asigna el valor 3 a la variable 'b'

# Llama a la función para factorizar la suma de cubos de 'a' y 'b' e imprime el resultado
print(factorizar_suma_cubos(a, b))

1^3 + 3^3 = (1 + 3)(1 - 3 + 9)


In [17]:
# Factoriza la diferencia de cubos 𝑔 ( 𝑦 ) = 𝑦 3 − 64

import sympy as sp

def factorizar_diferencia_cubos():
    y = sp.symbols('y')
    expr = y**3 - 64
    factorizada = sp.factor(expr)
    return expr, factorizada

original, factorizada = factorizar_diferencia_cubos()
print(f"Original: {original}")
print(f"Factorizada: {factorizada}")

Original: y**3 - 64
Factorizada: (y - 4)*(y**2 + 4*y + 16)


In [18]:
#Factorización LU (Descomposición de una matriz en una matriz triangular inferior y superior):

import numpy as np
from scipy.linalg import lu

# Definimos una matriz A
A = np.array([[2, 3, 1], [4, 7, 5], [6, 11, 7]])

# Aplicamos la factorización LU
P, L, U = lu(A)

# Mostramos los resultados
print("Matriz A:")
print(A)
print("\nMatriz P (permutación):")
print(P)
print("\nMatriz L (triangular inferior):")
print(L)
print("\nMatriz U (triangular superior):")
print(U)
print("\nVerificación: P * L * U")
print(np.dot(P, np.dot(L, U)))

Matriz A:
[[ 2  3  1]
 [ 4  7  5]
 [ 6 11  7]]

Matriz P (permutación):
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Matriz L (triangular inferior):
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]]

Matriz U (triangular superior):
[[ 6.         11.          7.        ]
 [ 0.         -0.66666667 -1.33333333]
 [ 0.          0.          1.        ]]

Verificación: P * L * U
[[ 2.  3.  1.]
 [ 4.  7.  5.]
 [ 6. 11.  7.]]


In [19]:
# Matriz A:
# [[1 2]
#  [3 4]
#  [5 6]]

# Matriz U:
# [[-0.2298477   0.88346102  0.40824829]
#  [-0.52474482  0.24078249 -0.81649658]
#  [-0.81964194 -0.40189603  0.40824829]]

# Matriz S (valores singulares):
# [[9.52551809 0.        ]
#  [0.         0.51430058]
#  [0.         0.        ]]

# Matriz VT (transpuesta de la matriz de vectores singulares):
# [[-0.61962948 -0.78489445]
#  [-0.78489445  0.61962948]]

# Verificación: U * S * VT
# [[1. 2.]
#  [3. 4.]
#  [5. 6.]]

import numpy as np

# Definimos una matriz A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Aplicamos la factorización SVD utilizando la función svd de numpy
U, S, VT = np.linalg.svd(A)

# Convertimos S en una matriz diagonal completa de la misma dimensión que A
# Inicializamos una matriz llena de ceros con la misma forma que A
S_matrix = np.zeros(A.shape)

# Llenamos los elementos diagonales de S_matrix con los valores singulares de S
# np.diag(S) crea una matriz diagonal a partir del vector S
S_matrix[:len(S), :len(S)] = np.diag(S)

# Reconstruimos la matriz original multiplicando U, S (convertida a matriz), y VT
# Usamos el operador @ para multiplicación matricial
A_reconstructed = U @ S_matrix @ VT

# Mostramos los resultados
print("Matriz A:")
print(A)
print("\nMatriz U:")
print(U)
print("\nMatriz S (valores singulares):")
print(S_matrix)
print("\nMatriz VT (transpuesta de la matriz de vectores singulares):")
print(VT)
print("\nVerificación: U * S * VT")
print(A_reconstructed)


Matriz A:
[[1 2]
 [3 4]
 [5 6]]

Matriz U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Matriz S (valores singulares):
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

Matriz VT (transpuesta de la matriz de vectores singulares):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

Verificación: U * S * VT
[[1. 2.]
 [3. 4.]
 [5. 6.]]
