Ejercicio 1: Factorización de Polinomios


Factoriza el siguiente polinomio cuadrado perfecto: [ x^2 + 14x + 49 ]


Este problema involucra un trinomio cuadrado perfecto, por lo que deberás reconocer la forma ( a^2 + 2ab + b^2 ) y factorizarlo.

In [1]:
from sympy import symbols, factor, expand, collect

x = symbols('x')

exp = x**2 + 14*x + 49
factored_exp = factor(exp)

print(f"Expresión original: {exp}")
print(f"Expresión factorizada: {factored_exp}")

Expresión original: x**2 + 14*x + 49
Expresión factorizada: (x + 7)**2


Ejercicio 2: Descomposición LU

Dada la matriz (A), aplica la descomposición LU y obtén las matrices (P), (L), y (U):

# Definir la matriz A
A = Matrix([
    [2, 4, -2],
    [-2, -1, 7],
    [10, 2, 1]
])

Este ejercicio implica realizar la factorización LU de la matriz (A).

In [6]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 3, 1], [4, 7, 5], [6, 11, 7]])

# Factorización LU
P, L, U = lu(A)

print("Matriz P:")
print(P)
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)

Matriz P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Matriz L:
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]]

Matriz U:
[[ 6.         11.          7.        ]
 [ 0.         -0.66666667 -1.33333333]
 [ 0.          0.          1.        ]]


Ejercicio 3: Factorización SVD

Dada la matriz (B), aplica la factorización de valores singulares (SVD) y obtén las matrices (U), (S), y (V^T):

[ B =
[123456] 
]

Este ejercicio requiere la aplicación de la factorización SVD a la matriz (B).

In [8]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


U, S, VT = np.linalg.svd(A)
print("\nMatriz U:")
print(U)
print("\nMatriz S:")
print(S)
print("\nMatriz VT:")
print(VT)


Matriz U:
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

Matriz S:
[9.508032   0.77286964]

Matriz VT:
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Ejercicio 4: Factorización de Polinomios

Factoriza el siguiente trinomio cuadrado perfecto: [ m^2 + 6m + 9 ]

Este problema se centra en reconocer y factorizar un trinomio cuadrado perfecto.

In [2]:
from sympy import symbols, factor, expand, collect

m = symbols('m')
exp = m**2 + 6*m + 9
factored_exp = factor(exp)

print(f"Expresión original: {exp}")
print(f"Expresión factorizada: {factored_exp}")

Expresión original: m**2 + 6*m + 9
Expresión factorizada: (m + 3)**2


Ejercicio 5: Descomposición en Valores Propios

Dada la matriz (C), encuentra los valores y vectores propios: 
[ C = [41−21] ]

Este ejercicio implica la descomposición en valores propios de la matriz (C).

In [11]:
from sympy import Matrix, pprint

# Paso 1: Definir la matriz C
C = Matrix([
    [4, 1],
    [-2, 1]
])
print("✅ Matriz C:")
print(C)

# Paso 2: Calcular valores y vectores propios
eigen = C.eigenvects()

# Paso 3: Mostrar resultados con explicaciones
print("\n🎯 Descomposición en Valores y Vectores Propios:\n")

for val in eigen:
    valor_propio = val[0]
    multiplicidad = val[1]
    vectores_propios = val[2]
    
    print(f"🟡 Valor propio encontrado: {valor_propio} (multiplicidad: {multiplicidad})")
    
    for vec in vectores_propios:
        print(f"🔹 Vector propio asociado: ")
        pprint(vec)
        print(f"📌 Esto significa que C · v = {valor_propio} · v\n")


✅ Matriz C:
Matrix([[4, 1], [-2, 1]])

🎯 Descomposición en Valores y Vectores Propios:

🟡 Valor propio encontrado: 2 (multiplicidad: 1)
🔹 Vector propio asociado: 
⎡-1/2⎤
⎢    ⎥
⎣ 1  ⎦
📌 Esto significa que C · v = 2 · v

🟡 Valor propio encontrado: 3 (multiplicidad: 1)
🔹 Vector propio asociado: 
⎡-1⎤
⎢  ⎥
⎣1 ⎦
📌 Esto significa que C · v = 3 · v



Ejercicio 6: Factorización de Polinomios

Factoriza el siguiente trinomio cuadrado perfecto: [ y^2 - 10y + 25 ]

Este problema implica factorizar un trinomio cuadrado perfecto relacionado con la forma ( a^2 - 2ab + b^2 ).

In [6]:
from sympy import symbols, factor, expand, collect

m = symbols('m')
exp = m**2 + 10*m + 25
factored_exp = factor(exp)

print(f"Expresión original: {exp}")
print(f"Expresión factorizada: {factored_exp}")

Expresión original: m**2 + 10*m + 25
Expresión factorizada: (m + 5)**2


Ejercicio 7: Factorización SVD

Dada la matriz (D), aplica la factorización de valores singulares (SVD) y obtén las matrices (U), (S), y (V^T):

[ D =[3214] ]

Este ejercicio requiere la aplicación de la factorización SVD a la matriz (D).

In [8]:
import numpy as np

A = np.array([
    [3, 2],
    [1, 4]
])


U, S, VT = np.linalg.svd(A)
print("\nMatriz U:")
print(U)
print("\nMatriz S:")
print(S)
print("\nMatriz VT:")
print(VT)


Matriz U:
[[-0.64074744 -0.76775173]
 [-0.76775173  0.64074744]]

Matriz S:
[5.11667274 1.95439508]

Matriz VT:
[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]


Ejercicio 8: Factorización de Polinomios

Factoriza el siguiente polinomio cuadrado perfecto: [ a^2 - 8a + 16 ]

Este problema se centra en reconocer y factorizar un trinomio cuadrado perfecto.

In [10]:
from sympy import symbols, factor, expand, collect

m = symbols('m')
exp = m**2 + 8*m + 16
factored_exp = factor(exp)

print(f"Expresión original: {exp}")
print(f"Expresión factorizada: {factored_exp}")

Expresión original: m**2 + 8*m + 16
Expresión factorizada: (m + 4)**2
