# Automatic Zoom
## Diplomatura en Machine Learning con Python  
### Guía de Ejercicios

### Ejercicio 1
Crear una matriz de 2X4 utilizando la librería de Numpy. Una vez creada mostrarla en pantalla con la función Print.

In [1]:
import numpy as np

matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


### Ejercicio 2
Crear una matriz de 2X3 con ceros utilizando la librería de Numpy. Nota: para este ejercicio podemos utilizar la función Zeros(). Probar crear una nueva matriz con la función ones() y ver qué sucede. Para ambos casos utilizar la función print para validar la matriz.

In [2]:
import numpy as np

matriz_ceros = np.zeros((2, 3))
matriz_unos = np.ones((2, 3))

print("Matriz de ceros:")
print(matriz_ceros)

print("\nMatriz de unos:")
print(matriz_unos)


Matriz de ceros:
[[0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos:
[[1. 1. 1.]
 [1. 1. 1.]]


### Ejercicio 3
Utilizando la librería de Numpy crear una matriz identidad utilizando la función Eyes().

In [3]:
import numpy as np

matriz_identidad = np.eye(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Ejercicio 4
Para la matriz creada en el Ejercicio 1 acceder a la fila Cero. Imprimir en pantalla el resultado.

In [4]:
fila_cero = matriz[0]
print(fila_cero)

[1 2 3 4]


### Ejercicio 5
Para la matriz creada en el Ejercicio 1 acceder a un elemento específico. Imprimir en pantalla el resultado.

In [5]:
elemento_especifico = matriz[0, 1]  # por ejemplo, fila 0, columna 1
print(elemento_especifico)

2


### Ejercicio 6
Probar de acceder a una porción de la fila para la Matriz creada en el Ejercicio 1.

In [6]:
porcion_fila = matriz[0, 1:3]  # elementos de la fila 0, columnas 1 y 2
print(porcion_fila)

[2 3]


### Ejercicio 7
Probar de acceder a una porción de la columna para la matriz creada en el Ejercicio 1.

### Ejercicio 8
Probar la función Size() para la matriz creada en el ejercicio 1 y ver que devuelve.

In [ ]:
porcion_columna = matriz[0:2, 2]  # elementos de la columna 2, filas 0 y 1
print(porcion_columna)

### Ejercicio 9
Probar la función Shape() para la matriz creada en el ejercicio 1 y ver que devuelve.

In [7]:
print(matriz.shape)

(2, 4)


### Ejercicio 10
Obtener el número Máximo de la matriz creada en el ejercicio 1.

### Ejercicio 11
Obtener el número Mínimo de la matriz creada en el ejercicio 1.

### Ejercicio 12
Obtener la media para la matriz creada en el ejercicio 1.

### Ejercicio 13
Modificar el elemento de la fila 1 columna 0 y colocar el valor 10.

### Ejercicio 14
Sustituir la fila 0 de la matriz creada en el Ejercicio 1 por los valores (10, 20, 30, 40).

### Ejercicio 15
Crear una nueva matriz de 2X2 y luego convertir la matriz en un vector utilizando la función flatten().

### Ejercicio 16
Para la matriz creada en el Ejercicio 15 obtener su traspuesta.

### Ejercicio 17
Crear 2 matrices y realizar la multiplicación entre ambas.