In [1]:
import numpy as np

In [2]:
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
matriz_ceros = np.zeros((2, 3))
matriz_unos = np.ones((2, 3))
print(matriz_ceros)
print(matriz_unos)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
matriz_identidad = np.eye(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
fila_cero = matriz[0]
print(fila_cero)

[1 2 3 4]


In [6]:
elemento_especifico = matriz[0, 1]
print(elemento_especifico)

2


In [7]:
porcion_fila = matriz[0, 1:3]
print(porcion_fila)

[2 3]


In [8]:
porcion_columna = matriz[0:2, 2]
print(porcion_columna)

[3 7]


In [9]:
print(matriz.size)

8


In [10]:
print(matriz.shape)

(2, 4)


In [11]:
print(matriz.max())

8


In [12]:
print(matriz.min())

1


In [13]:
print(matriz.mean())

4.5


In [14]:
matriz[1, 0] = 10
print(matriz)

[[ 1  2  3  4]
 [10  6  7  8]]


In [15]:
matriz[0] = [10, 20, 30, 40]
print(matriz)

[[10 20 30 40]
 [10  6  7  8]]


In [16]:
matriz2 = np.array([[1, 2], [3, 4]])
vector = matriz2.flatten()
print(vector)

[1 2 3 4]


In [17]:
print(matriz2.T)

[[1 3]
 [2 4]]


In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [19]:
print(a + b)

[[ 6  8]
 [10 12]]
